"""Anima DirectEdit node.

Image in, edited image out. Consumes ComfyUI's stock ``MODEL`` / ``CLIP`` /
``VAE`` sockets — pipe in the same loaders you'd use for a normal Anima
KSampler workflow (``UNETLoader``/``CLIPLoader``/``VAELoader`` or
``CheckpointLoaderSimple``). The tagger socket comes from the
``comfyui-anima-tagger`` package (``AnimaTaggerLoader``) — install it
alongside this package if you want on-image ψ_src derivation; otherwise
use ``prompt_src_override`` to supply ψ_src directly.

Pipeline mirrors ``scripts/edit.py``:

  IMAGE -> PIL                        (ComfyUI [B,H,W,C] in [0,1] -> PIL.RGB)
  tagger.predict_caption -> psi_src   (skipped if prompt_src_override is set;
                                       tagger comes from AnimaTaggerLoader in
                                       comfyui-anima-tagger)
  psi_tar = psi_src + ", " + edit_text
  bucket pick from source aspect ratio
  CLIP.tokenize / encode_from_tokens(return_dict=True) for psi_src/tar/neg
  diffusion_model.preprocess_text_embeds -> 512-padded crossattn embeds
  VAE.encode source -> z_clean
  invert(z_clean, embed_src) -> z_inv, delta_z
  edit_forward(z_inv[0], delta_z, embed_tar) -> z_edit
  VAE.decode z_edit -> ComfyUI IMAGE [1,H,W,3] in [0,1]
"""

from __future__ import annotations

import importlib
import logging
import sys
from pathlib import Path
from typing import Tuple

import numpy as np
import torch

# Resolve where to import ``library.*`` from.
#
# Two install shapes are supported:
#
# 1. **Inside the anima_lora repo** (dev / monorepo install). This file lives
#    at ``anima_lora/custom_nodes/comfyui-anima-directedit/nodes.py`` so
#    ``parents[1]`` of HERE is the repo root, and the live ``library/`` is
#    reachable.
# 2. **Standalone ComfyUI install** (just dropped this folder into
#    ``ComfyUI/custom_nodes/``). Then ``parents[1]`` is ``ComfyUI/custom_nodes/``
#    which has no ``library/`` — fall back to the bundled inference subset
#    under ``_vendor/``. The vendor tree is generated by
#    ``scripts/sync_vendor.py`` in the parent repo and ships with the
#    published node version.
HERE = Path(__file__).resolve().parent
ANIMA_LORA = HERE.parents[1]
VENDOR = HERE / "_vendor"


def _resolve_anima_modules():
    """Return the live ``library`` modules if reachable, else the bundled
    vendor copies. Vendor wins only when the live import fails — in-repo
    edits to ``library/...`` are picked up automatically during development."""
    if str(ANIMA_LORA) not in sys.path:
        sys.path.insert(0, str(ANIMA_LORA))

    def _imports():
        anima_tagger = importlib.import_module("library.captioning.anima_tagger")
        buckets_mod = importlib.import_module("library.datasets.buckets")
        directedit_mod = importlib.import_module("library.inference.directedit")
        sampling_mod = importlib.import_module("library.inference.sampling")
        return anima_tagger, buckets_mod, directedit_mod, sampling_mod

    try:
        return _imports()
    except ImportError:
        if not VENDOR.exists():
            raise
        if str(VENDOR) not in sys.path:
            sys.path.insert(0, str(VENDOR))
        # Drop any partially-imported modules so the vendor tree's copies
        # actually load (the live attempt may have cached half a tree).
        for k in [
            k for k in list(sys.modules)
            if k.startswith(("library.", "networks."))
            or k in ("library", "networks")
        ]:
            del sys.modules[k]
        return _imports()


from PIL import Image  # noqa: E402

import comfy.model_management  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI
import comfy.utils  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI

(
    _anima_tagger_mod,
    _buckets_mod,
    directedit,
    inference_utils,
) = _resolve_anima_modules()
AnimaTagger = _anima_tagger_mod.AnimaTagger
CONSTANT_TOKEN_BUCKETS = _buckets_mod.CONSTANT_TOKEN_BUCKETS

logger = logging.getLogger(__name__)


def _pick_bucket(pil_img: Image.Image) -> Tuple[int, int]:
    """Closest CONSTANT_TOKEN_BUCKETS entry by aspect ratio. Returns (H, W)."""
    rw, rh = pil_img.size
    target = rw / rh
    best = min(CONSTANT_TOKEN_BUCKETS, key=lambda wh: abs(wh[0] / wh[1] - target))
    return best[1], best[0]  # bucket is (W, H); we return (H, W)


def _comfy_image_to_pil(image_tensor: torch.Tensor) -> Image.Image:
    """ComfyUI IMAGE [B, H, W, C] in [0,1] -> PIL.RGB (first batch element)."""
    arr = image_tensor[0].clamp(0, 1).cpu().numpy()
    return Image.fromarray((arr * 255).astype(np.uint8)).convert("RGB")


def _pil_to_comfy_image(pil_img: Image.Image) -> torch.Tensor:
    """PIL.RGB -> ComfyUI IMAGE [1, H, W, 3] in [0,1] (for VAE.encode input)."""
    arr = np.asarray(pil_img.convert("RGB"), dtype=np.float32) / 255.0
    return torch.from_numpy(arr).unsqueeze(0)


def _encode_prompt_comfy(
    clip, unet, text: str, device: torch.device, dtype: torch.dtype
) -> torch.Tensor:
    """Tokenize + encode + LLMAdapter preprocess via the comfy CLIP socket.

    Mirrors ``model_base.Anima.extra_conds`` exactly: comfy's path passes
    only ``t5xxl_weights`` to ``preprocess_text_embeds`` (no Qwen3 source
    mask, no T5 attention mask), so the LLMAdapter's cross-attention sees
    every Qwen3 padding embedding. That divergence from the library path
    (which masks both sides + zeros source padding before the adapter) is
    the leading suspect when the node reconstructs the source instead of
    applying the edit. Use ``_encode_prompt_library`` to A/B test.
    """
    tokens = clip.tokenize(text)
    out = clip.encode_from_tokens(tokens, return_pooled=False, return_dict=True)
    cond = out["cond"]  # [1, T_q, 1024]
    t5xxl_ids = out["t5xxl_ids"]  # [T_t5]
    t5xxl_weights = out["t5xxl_weights"]  # [T_t5]

    # Mirror model_base.Anima.extra_conds shape conventions.
    t5xxl_ids = t5xxl_ids.unsqueeze(0).to(device)  # [1, T_t5]
    t5xxl_weights = t5xxl_weights.unsqueeze(0).unsqueeze(-1).to(device, dtype=dtype)
    cond = cond.to(device, dtype=dtype)

    embed = unet.preprocess_text_embeds(cond, t5xxl_ids, t5xxl_weights=t5xxl_weights)
    return embed


def _encode_prompt_library(
    library_te,
    library_tokenize,
    unet,
    text: str,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    """Replicate ``library.inference.text.prepare_text_inputs`` end-to-end.

    1. Tokenize with the library's ``AnimaTokenizeStrategy`` (Qwen3 + T5,
       both padded to 512).
    2. Encode Qwen3 ids through the loaded library text encoder; zero out
       Qwen3 padding embeddings (the library's encoder strategy does this
       at line 137 of library/anima/strategy.py — comfy's path doesn't).
    3. Run ``unet.llm_adapter`` with BOTH source + target attention masks
       (comfy's ``preprocess_text_embeds`` skips both — paper-validated
       inputs come from the masked path).
    4. Zero out T5 padding positions in the adapter output, pad to 512.

    The resulting ``[1, 512, 1024]`` matches what the CLI's
    ``prepare_text_inputs`` feeds DirectEdit. Lets us A/B against the
    comfy CLIP path when the node reconstructs the source.
    """
    qwen_ids, qwen_mask, t5_ids, t5_mask = library_tokenize.tokenize(text)
    qwen_ids = qwen_ids.to(library_te.device)
    qwen_mask = qwen_mask.to(library_te.device)
    with torch.no_grad():
        prompt_embeds = library_te(
            input_ids=qwen_ids, attention_mask=qwen_mask
        ).last_hidden_state
        prompt_embeds[~qwen_mask.bool()] = 0  # zero Qwen3 padding (line 137)

        prompt_embeds = prompt_embeds.to(device, dtype=dtype)
        t5_ids = t5_ids.to(device)
        t5_mask = t5_mask.to(device)
        qwen_mask_d = qwen_mask.to(device)

        # `unet` is the comfy Anima DiT — its `llm_adapter` accepts the same
        # mask-aware kwargs as the library Anima's adapter.
        crossattn = unet.llm_adapter(
            prompt_embeds,
            t5_ids,
            target_attention_mask=t5_mask,
            source_attention_mask=qwen_mask_d,
        )
        crossattn[~t5_mask.bool()] = 0
        if crossattn.shape[1] < 512:
            crossattn = torch.nn.functional.pad(
                crossattn, (0, 0, 0, 512 - crossattn.shape[1])
            )
    return crossattn.to(device, dtype=dtype)


class AnimaDirectEdit:
    """Image + tag-to-add -> edited image, driven by stock MODEL/CLIP/VAE sockets."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("MODEL", {"tooltip": "Anima DiT (e.g. UNETLoader)."}),
                "clip": ("CLIP", {"tooltip": "Anima CLIP (Qwen3 06B + T5xxl tokenizer)."}),
                "vae": ("VAE", {"tooltip": "Qwen Image VAE."}),
                "image": ("IMAGE",),
                "edit_text": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "double peace",
                        "tooltip": (
                            "Tag(s) to add to the source caption. "
                            "psi_tar = psi_src + ', ' + edit_text. Leave "
                            "empty to use psi_src as-is (sanity-check; "
                            "should reconstruct the source)."
                        ),
                    },
                ),
                "negative_prompt": (
                    "STRING",
                    {"multiline": True, "default": "worst quality"},
                ),
                "infer_steps": ("INT", {"default": 28, "min": 1, "max": 200}),
                "flow_shift": (
                    "FLOAT",
                    {"default": 1.0, "min": 0.1, "max": 10.0, "step": 0.05},
                ),
                "guidance_scale": (
                    "FLOAT",
                    {
                        "default": 4.0,
                        "min": 1.0,
                        "max": 20.0,
                        "step": 0.1,
                        "tooltip": "CFG scale for the edit (target) pass.",
                    },
                ),
                "invert_guidance": (
                    "FLOAT",
                    {
                        "default": 1.0,
                        "min": 1.0,
                        "max": 20.0,
                        "step": 0.1,
                        "tooltip": (
                            "CFG scale during inversion. Default 1.0 (no CFG); "
                            "raise only if the inverted noise must match a "
                            "high-CFG generation seed."
                        ),
                    },
                ),
                "seed": ("INT", {"default": 42, "min": 0, "max": 2**63 - 1}),
                "t_inj": (
                    "INT",
                    {
                        "default": 0,
                        "min": 0,
                        "max": 200,
                        "tooltip": (
                            "Number of early steps to inject src self-attn V "
                            "into the tar pass (paper Eq. 13). 0 = pure "
                            "ΔZ-anchored edit. Typical: t_inj ≈ T/10..T/3 "
                            "(e.g. 3..9 at infer_steps=28). Higher = stronger "
                            "source-feature preservation, weaker edit "
                            "leverage. Injects at all DiT blocks except the "
                            "final (SD3.5-style default)."
                        ),
                    },
                ),
            },
            "optional": {
                "tagger": (
                    "ANIMA_TAGGER",
                    {
                        "tooltip": (
                            "AnimaTagger from AnimaTaggerLoader (in the "
                            "comfyui-anima-tagger package). Required unless "
                            "prompt_src_override is set."
                        ),
                    },
                ),
                "prompt_src_override": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "tooltip": (
                            "Optional: replace the tagger's caption with your "
                            "own psi_src. Leave empty to use the tagger output. "
                            "Useful when the source is an Anima-generated image "
                            "and you already know the original prompt. If set, "
                            "the tagger socket is ignored."
                        ),
                    },
                ),
                "library_text_encoder_path": (
                    "STRING",
                    {
                        "multiline": False,
                        "default": "",
                        "tooltip": (
                            "Optional: path to the library's Qwen3 text "
                            "encoder safetensors (e.g. "
                            "`models/text_encoders/qwen_3_06b_base.safetensors`). "
                            "If set, bypasses the comfy CLIP socket and "
                            "encodes through `library.inference.text."
                            "prepare_text_inputs` — same path the working "
                            "CLI (`scripts/edit.py`) uses. Required when the "
                            "node returns a source-equivalent result while "
                            "the CLI works: the comfy CLIP path skips the "
                            "Qwen3 source mask + T5 attention mask in "
                            "LLMAdapter, which can collapse ψ_tar onto ψ_src."
                        ),
                    },
                ),
            },
        }

    RETURN_TYPES = ("LATENT", "STRING", "STRING")
    RETURN_NAMES = ("latent", "prompt_src", "prompt_tar")
    FUNCTION = "edit"
    CATEGORY = "anima"
    DESCRIPTION = (
        "DirectEdit (Yang & Ye arXiv:2605.02417) editor for Anima. Runs the "
        "AnimaTagger on the source image to derive psi_src, appends edit_text "
        "to form psi_tar, then performs flow inversion + delta_z-anchored "
        "resampling on the MODEL/CLIP/VAE sockets you wire in. Returns the "
        "edited LATENT — wire it into VAEDecode (or any latent-consuming node) "
        "to render. Returning latent (not image) keeps decode shape handling "
        "with the stock node and lets you compare z_edit against z_clean."
    )

    def edit(
        self,
        model,
        clip,
        vae,
        image: torch.Tensor,
        edit_text: str,
        negative_prompt: str,
        infer_steps: int,
        flow_shift: float,
        guidance_scale: float,
        invert_guidance: float,
        seed: int,
        t_inj: int = 0,
        tagger: AnimaTagger | None = None,
        prompt_src_override: str = "",
        library_text_encoder_path: str = "",
    ):
        device = comfy.model_management.get_torch_device()
        dtype = torch.bfloat16

        pil_src = _comfy_image_to_pil(image)

        if prompt_src_override.strip():
            psi_src = prompt_src_override.strip()
            logger.info("DirectEdit: using prompt_src_override: %r", psi_src)
        else:
            if tagger is None:
                raise ValueError(
                    "AnimaDirectEdit needs either a `tagger` socket "
                    "(from AnimaTaggerLoader in the comfyui-anima-tagger "
                    "package) or a non-empty `prompt_src_override` to "
                    "derive psi_src."
                )
            logger.info("DirectEdit: running AnimaTagger from %s", tagger.ckpt_dir)
            psi_src = tagger.predict_caption(pil_src)
            logger.info("DirectEdit: psi_src = %r", psi_src)

        edit = (edit_text or "").strip()
        psi_tar = f"{psi_src}, {edit}" if edit else psi_src
        logger.info("DirectEdit: psi_tar = %r", psi_tar)

        h_pix, w_pix = _pick_bucket(pil_src)
        pil_src_resized = pil_src.resize((w_pix, h_pix), Image.LANCZOS)
        logger.info(
            "DirectEdit: bucket %dx%d (HxW) for source aspect %.3f",
            h_pix, w_pix, pil_src.size[0] / pil_src.size[1],
        )

        # Bring DiT onto device so preprocess_text_embeds (LLMAdapter) and the
        # invert/edit forwards see resident weights. ComfyUI's patcher owns
        # eviction — we don't move it back.
        comfy.model_management.load_models_gpu([model])
        unet = model.model.diffusion_model

        torch.manual_seed(seed)

        if library_text_encoder_path.strip():
            logger.info(
                "DirectEdit: encoding prompts via library TE (%s) — "
                "bypassing comfy CLIP socket",
                library_text_encoder_path,
            )
            from library.anima import strategy as _strat
            from library.inference.models import load_text_encoder as _load_te
            from types import SimpleNamespace as _NS

            te_args = _NS(
                text_encoder=library_text_encoder_path.strip(),
                lora_weight=None,
                lora_multiplier=1.0,
            )
            library_te = _load_te(te_args, dtype=dtype, device=device)
            library_tokenize = _strat.AnimaTokenizeStrategy(
                qwen3_path=library_text_encoder_path.strip(),
                t5_tokenizer_path=None,
                qwen3_max_length=512,
                t5_max_length=512,
            )
            with torch.no_grad():
                embed_src = _encode_prompt_library(
                    library_te, library_tokenize, unet, psi_src, device, dtype
                )
                embed_tar = _encode_prompt_library(
                    library_te, library_tokenize, unet, psi_tar, device, dtype
                )
                embed_neg = _encode_prompt_library(
                    library_te, library_tokenize, unet, negative_prompt, device, dtype
                )
            del library_te, library_tokenize
            comfy.model_management.soft_empty_cache()
        else:
            logger.info("DirectEdit: encoding prompts via comfy CLIP socket")
            with torch.no_grad():
                embed_src = _encode_prompt_comfy(clip, unet, psi_src, device, dtype)
                embed_tar = _encode_prompt_comfy(clip, unet, psi_tar, device, dtype)
                embed_neg = _encode_prompt_comfy(clip, unet, negative_prompt, device, dtype)

        # Diagnostic: if ψ_src and ψ_tar collapse to the same embedding, the
        # edit pass will reconstruct the source by design (Δz anchors + same
        # velocity field == identity). Big abs-mean diff = encoder is doing
        # its job; near-zero = encoder path is the bug.
        with torch.no_grad():
            d_st = (embed_src.float() - embed_tar.float()).abs().mean().item()
            d_sn = (embed_src.float() - embed_neg.float()).abs().mean().item()
            d_tn = (embed_tar.float() - embed_neg.float()).abs().mean().item()
        logger.info(
            "DirectEdit embed diffs (abs mean): "
            "|src-tar|=%.6f  |src-neg|=%.6f  |tar-neg|=%.6f  "
            "(src.norm=%.3f tar.norm=%.3f shape=%s)",
            d_st, d_sn, d_tn,
            embed_src.float().norm().item(),
            embed_tar.float().norm().item(),
            tuple(embed_src.shape),
        )
        if d_st < 1e-4:
            logger.warning(
                "DirectEdit: |src-tar| < 1e-4 — embeddings are effectively "
                "identical, edit pass will reconstruct the source. Check "
                "psi_src/psi_tar strings (logged above) and try setting "
                "library_text_encoder_path to bypass the comfy CLIP."
            )

        logger.info("DirectEdit: encoding source image via VAE")
        img_in = _pil_to_comfy_image(pil_src_resized)
        z_clean = vae.encode(img_in)  # [1, C_lat, T=1, H/8, W/8]
        z_clean = z_clean.to(device, dtype=dtype)
        logger.info("DirectEdit: encoded source latent %s", tuple(z_clean.shape))

        timesteps, sigmas = inference_utils.get_timesteps_sigmas(
            infer_steps, flow_shift, device
        )
        sigmas = sigmas.to(device)

        logger.info(
            "DirectEdit: invert (T=%d, src_guidance=%.2f) -> edit "
            "(tar_guidance=%.2f, t_inj=%d)",
            infer_steps, invert_guidance, guidance_scale, t_inj,
        )
        # Two-phase progress bar: invert occupies [0, T), edit occupies [T, 2T).
        pbar = comfy.utils.ProgressBar(infer_steps * 2)
        z_inv, delta_z = directedit.invert(
            anima=unet,
            z_clean=z_clean,
            embed_src=embed_src,
            embed_neg=embed_neg if invert_guidance != 1.0 else None,
            sigmas=sigmas,
            guidance_scale=invert_guidance,
            step_callback=lambda step, total: pbar.update_absolute(step),
        )
        z_edit = directedit.edit_forward(
            anima=unet,
            z_init=z_inv[0],
            delta_z=delta_z,
            embed_tar=embed_tar,
            embed_neg=embed_neg,
            sigmas=sigmas,
            guidance_scale=guidance_scale,
            embed_src=embed_src if t_inj > 0 else None,
            t_inj=t_inj,
            # t_inj_blocks=None → directedit defaults to all-but-last (SD3.5 style).
            step_callback=lambda step, total: pbar.update_absolute(infer_steps + step),
        )

        # Return the edited LATENT — caller wires VAEDecode. Anima's latent
        # is 5D [B, C, T=1, H/8, W/8]; the stock LATENT dict format uses
        # `samples` and tolerates 5D for video VAEs.
        logger.info("DirectEdit: returning edited latent %s", tuple(z_edit.shape))
        return ({"samples": z_edit.to(dtype=dtype).cpu()}, psi_src, psi_tar)


NODE_CLASS_MAPPINGS = {
    "AnimaDirectEdit": AnimaDirectEdit,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnimaDirectEdit": "Anima DirectEdit",
}
