"""Anima Tagger ComfyUI nodes.

Two nodes:

* ``AnimaTaggerLoader`` - load an ``AnimaTagger`` checkpoint from disk and
  emit a reusable ``ANIMA_TAGGER`` socket. ComfyUI memoizes loader outputs
  by inputs, so the tagger persists across graph runs without per-call
  reload.
* ``AnimaTaggerCaption`` - take an ``ANIMA_TAGGER`` and an ``IMAGE`` and
  return the predicted caption as a ``STRING``. Useful outside DirectEdit
  (e.g., feeding any sampler's text input or pre-filling LoRA captions).

The ``ANIMA_TAGGER`` socket type is a plain string in ComfyUI's type
system, so the AnimaDirectEdit node in ``comfyui-anima-directedit`` consumes
the same socket without a code-level dependency on this package.
"""

from __future__ import annotations

import importlib
import logging
import sys
from pathlib import Path

import numpy as np
import torch

# Resolve where to import ``library.captioning.anima_tagger`` from.
#
# Two install shapes are supported:
#
# 1. **Inside the anima_lora repo** (dev / monorepo install). This file lives
#    at ``anima_lora/custom_nodes/comfyui-anima-tagger/nodes.py`` so
#    ``parents[2]`` is the repo root, and the live ``library/`` is reachable.
# 2. **Standalone ComfyUI install** (just dropped this folder into
#    ``ComfyUI/custom_nodes/``). Then ``parents[2]`` is ``ComfyUI/custom_nodes/``
#    which has no ``library/`` - fall back to the bundled inference subset
#    under ``_vendor/``. The vendor tree is generated by
#    ``scripts/sync_tagger_vendor.py`` in the parent repo and ships with the
#    published node version.
HERE = Path(__file__).resolve().parent
ANIMA_LORA = HERE.parents[1]
VENDOR = HERE / "_vendor"

# HF repo we auto-fetch the tagger checkpoint from when ``tagger_dir`` is
# missing required files. Mirrors the PE-Core auto-fetch already in this
# loader - the user gets a working node out of the box without manual
# downloads, while still being able to point ``tagger_dir`` at a
# custom-trained checkpoint.
_HF_TAGGER_REPO = "sorryhyun/anima-tagger"
_REQUIRED_FILES = ("config.json", "model.safetensors", "vocab.json", "rules.yaml")
_OPTIONAL_FILES = ("thresholds.safetensors", "groups.yaml", "pe_lora.safetensors")

# Sentinel shown at the top of the pe_lora dropdown — empty string survives
# the existing "if pe_lora_path.strip():" gate in load(), which falls back
# to <tagger_dir>/pe_lora.safetensors. Kept readable as a label rather than
# bare "" so the UI doesn't show a blank first row.
_PE_LORA_DEFAULT_LABEL = "(default: <tagger_dir>/pe_lora.safetensors)"


def _list_pe_lora_files() -> list[str]:
    """Discoverable PE-LoRA safetensors candidates, as repo-relative paths.

    Globs the locations where PE-LoRA deltas naturally live:

    * ``models/captioners/<ckpt>/pe_lora*.safetensors`` — colocated with
      a tagger checkpoint, the train-pe-lora default. Most common case.
    * ``models/pe_loras/*.safetensors`` — optional dedicated dir for
      users who keep multiple deltas around without nesting them under
      a tagger checkpoint.
    * ``output/ckpt/*pe_lora*.safetensors`` — training output sweeps.

    Returns paths relative to ``ANIMA_LORA`` so the load() resolver
    (which already prepends ``ANIMA_LORA`` for non-absolute inputs)
    accepts them unchanged.

    Empty when running standalone (no anima_lora repo) — caller adds the
    default sentinel so the dropdown is never empty.
    """
    if not ANIMA_LORA.exists():
        return []
    seen: set[str] = set()
    out: list[str] = []
    glob_patterns = (
        "models/captioners/*/pe_lora*.safetensors",
        "models/captioners/*/*pe_lora*.safetensors",
        "models/pe_loras/*.safetensors",
        "output/ckpt/*pe_lora*.safetensors",
    )
    for pattern in glob_patterns:
        for p in sorted(ANIMA_LORA.glob(pattern)):
            rel = str(p.relative_to(ANIMA_LORA))
            if rel not in seen:
                seen.add(rel)
                out.append(rel)
    return out


def _ensure_tagger_dir(tdir: Path) -> None:
    """If ``tdir`` is missing any required tagger file, fetch the whole
    checkpoint from ``sorryhyun/anima-tagger`` into it.

    Optional files (``thresholds.safetensors``, ``groups.yaml``,
    ``pe_lora.safetensors``) are best-effort - a 404 on the repo just means
    the published checkpoint doesn't ship that file (e.g. ``pe_lora.safetensors``
    when ``config.pe_lora=false``). The required-file gate already guarantees
    the tagger can load.
    """
    if all((tdir / f).exists() for f in _REQUIRED_FILES):
        return
    from huggingface_hub import hf_hub_download
    from huggingface_hub.utils import EntryNotFoundError

    logger.info(
        "AnimaTaggerLoader: %s is missing required files - fetching %s "
        "(one-time).",
        tdir,
        _HF_TAGGER_REPO,
    )
    tdir.mkdir(parents=True, exist_ok=True)
    for fname in _REQUIRED_FILES:
        hf_hub_download(
            repo_id=_HF_TAGGER_REPO,
            filename=fname,
            local_dir=str(tdir),
        )
    for fname in _OPTIONAL_FILES:
        try:
            hf_hub_download(
                repo_id=_HF_TAGGER_REPO,
                filename=fname,
                local_dir=str(tdir),
            )
        except EntryNotFoundError:
            logger.debug("optional file %s not present on %s", fname, _HF_TAGGER_REPO)


def _resolve_anima_tagger():
    """Return the ``AnimaTagger`` class from the live tree if reachable,
    else from the bundled vendor copy. Vendor wins only when the live import
    fails - keeps in-repo edits picked up automatically during development."""
    if str(ANIMA_LORA) not in sys.path:
        sys.path.insert(0, str(ANIMA_LORA))
    try:
        return importlib.import_module("library.captioning.anima_tagger").AnimaTagger
    except ImportError:
        if not VENDOR.exists():
            raise
        if str(VENDOR) not in sys.path:
            sys.path.insert(0, str(VENDOR))
        return importlib.import_module("library.captioning.anima_tagger").AnimaTagger


from PIL import Image  # noqa: E402

import comfy.model_management  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI

AnimaTagger = _resolve_anima_tagger()  # noqa: E402

logger = logging.getLogger(__name__)


def _comfy_image_to_pil(image_tensor: torch.Tensor) -> Image.Image:
    """ComfyUI IMAGE [B, H, W, C] in [0,1] -> PIL.RGB (first batch element)."""
    arr = image_tensor[0].clamp(0, 1).cpu().numpy()
    return Image.fromarray((arr * 255).astype(np.uint8)).convert("RGB")


class AnimaTaggerLoader:
    """Load an AnimaTagger checkpoint as a reusable graph asset.

    ComfyUI memoizes loader outputs by inputs, so the tagger persists across
    invocations as long as ``tagger_dir`` doesn't change - no per-call
    reload from disk.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "tagger_dir": (
                    "STRING",
                    {
                        "default": "models/captioners/anima-tagger-v1",
                        "tooltip": (
                            "AnimaTagger checkpoint directory. Relative paths "
                            "are resolved against the anima_lora/ project root; "
                            "absolute paths used as-is. If the directory is "
                            "missing required files, the checkpoint is "
                            f"auto-fetched from {_HF_TAGGER_REPO} on first use."
                        ),
                    },
                ),
                "pe_ckpt": (
                    "STRING",
                    {
                        "default": "models/pe/PE-Core-L14-336.pt",
                        "tooltip": (
                            "PE-Core-L14-336 vision-encoder checkpoint (.pt). "
                            "Relative paths resolve against the anima_lora/ "
                            "root; absolute paths used as-is. If the file is "
                            "missing, it's auto-fetched from "
                            "facebook/PE-Core-L14-336 on first use (one-time "
                            "~1 GB download)."
                        ),
                    },
                ),
                "use_pe_lora": (
                    "BOOLEAN",
                    {
                        "default": True,
                        "label_on": "on",
                        "label_off": "off",
                        "tooltip": (
                            "Master on/off for PE-LoRA injection. When off, "
                            "the encoder runs as the bare frozen PE-Core and "
                            "pe_lora_path is ignored — useful when the "
                            "selected sidecar is missing / renamed and "
                            "ComfyUI would otherwise reject the empty "
                            "dropdown selection."
                        ),
                    },
                ),
                "pe_lora_path": (
                    [_PE_LORA_DEFAULT_LABEL] + _list_pe_lora_files(),
                    {
                        "tooltip": (
                            "PE-LoRA sidecar override (safetensors). The "
                            "default entry uses "
                            "<tagger_dir>/pe_lora.safetensors (shipped or "
                            "auto-fetched by train-pe-lora); the remaining "
                            "rows are PE-LoRA files discovered under "
                            "models/captioners/*/, models/pe_loras/, and "
                            "output/ckpt/. Has no effect when use_pe_lora "
                            "is off, or unless config.json in tagger_dir "
                            "has 'pe_lora: true' (rank / alpha / target "
                            "layers all come from that config)."
                        ),
                    },
                ),
            },
        }

    RETURN_TYPES = ("ANIMA_TAGGER",)
    RETURN_NAMES = ("tagger",)
    FUNCTION = "load"
    CATEGORY = "anima"
    DESCRIPTION = (
        "Load an AnimaTagger checkpoint. Output socket is consumed by "
        "AnimaTaggerCaption (image -> caption) and AnimaDirectEdit. ComfyUI "
        "memoizes the output, so re-running the graph reuses the same "
        "instance without reloading. Both the tagger checkpoint "
        f"({_HF_TAGGER_REPO}) and the PE-Core-L14-336 vision encoder are "
        "auto-downloaded if their paths don't exist yet."
    )

    def load(
        self,
        tagger_dir: str,
        pe_ckpt: str,
        use_pe_lora: bool = True,
        pe_lora_path: str = "",
    ):
        tdir = Path(tagger_dir)
        if not tdir.is_absolute():
            tdir = ANIMA_LORA / tdir
        pe_path = Path(pe_ckpt)
        if not pe_path.is_absolute():
            pe_path = ANIMA_LORA / pe_path
        # Dropdown's "default" sentinel maps to the colocated fallback inside
        # AnimaTagger (None override -> <ckpt_dir>/pe_lora.safetensors). When
        # use_pe_lora is off, the dropdown is ignored entirely and the
        # tagger is told to skip PE-LoRA injection.
        pe_lora_resolved: Path | None = None
        if use_pe_lora:
            pl_str = pe_lora_path.strip()
            if pl_str and pl_str != _PE_LORA_DEFAULT_LABEL:
                pl = Path(pl_str)
                if not pl.is_absolute():
                    pl = ANIMA_LORA / pl
                pe_lora_resolved = pl
        _ensure_tagger_dir(tdir)
        device = comfy.model_management.get_torch_device()
        logger.info(
            "AnimaTaggerLoader: loading %s on %s (pe=%s, pe_lora=%s)",
            tdir,
            device,
            pe_path,
            "<disabled>" if not use_pe_lora else pe_lora_resolved,
        )
        tagger = AnimaTagger(
            ckpt_dir=tdir,
            device=device,
            pe_ckpt=pe_path,
            pe_lora_path=pe_lora_resolved,
            pe_lora_disabled=not use_pe_lora,
        )
        return (tagger,)


class AnimaTaggerCaption:
    """Run an AnimaTagger over an image and emit the caption as a STRING."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "tagger": (
                    "ANIMA_TAGGER",
                    {"tooltip": "AnimaTagger from AnimaTaggerLoader."},
                ),
                "image": ("IMAGE",),
            },
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("caption",)
    FUNCTION = "caption"
    CATEGORY = "anima"
    DESCRIPTION = (
        "Predict an Anima-formatted caption for an image using AnimaTagger. "
        "Output is a comma-separated tag string in Anima's canonical slot "
        "order (rating, count, characters, copyrights, @artists, generals) "
        "with underscores replaced by spaces - drop-in for any STRING input "
        "(CLIPTextEncode, prompt_src_override on AnimaDirectEdit, etc.)."
    )

    def caption(self, tagger: AnimaTagger, image: torch.Tensor):
        pil = _comfy_image_to_pil(image)
        text = tagger.predict_caption(pil)
        logger.info("AnimaTaggerCaption: %r", text)
        return (text,)


NODE_CLASS_MAPPINGS = {
    "AnimaTaggerLoader": AnimaTaggerLoader,
    "AnimaTaggerCaption": AnimaTaggerCaption,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnimaTaggerLoader": "Anima Tagger Loader",
    "AnimaTaggerCaption": "Anima Tagger Caption",
}
